# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akirachix', '0003_auto_20171017_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
